kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  annotations:
    app.openshift.io/vcs-uri: 'https://github.com/jmetso/rhbk-gitops.git'
    argocd.argoproj.io/sync-wave: "200"
  name: postgresql
  finalizers:
    - kubernetes.io/pvc-protection
  labels:
    app: tasklist
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem

