apiVersion: v1
kind: Secret
metadata:
  annotations:
    app.openshift.io/vcs-uri: 'https://github.com/jmetso/rhbk-gitops.git'
    argocd.argoproj.io/sync-wave: "200"
  labels:
    app: sso
    app.kubernetes.io/component: database
    app.kubernetes.io/instance: sso
    app.kubernetes.io/part-of: sso
  name: postgresql
stringData:
  database-name: keycloak
  database-password: 5up3r53cr3t
  database-user: keycloak
