kind: Service
apiVersion: v1
metadata:
  name: postgresql
  labels:
    app: sso
    app.kubernetes.io/name: sso
    app.kubernetes.io/component: database
    app.kubernetes.io/instance: sso
  annotations:
    app.openshift.io/vcs-uri: 'https://github.com/jmetso/rhbk-gitops.git'
    argocd.argoproj.io/sync-wave: "200"
spec:
  ipFamilies:
    - IPv4
  ports:
    - name: postgresql
      protocol: TCP
      port: 5432
      targetPort: 5432
  internalTrafficPolicy: Cluster
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    name: postgresql

