apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rhbk-tls-certificate
spec:
  commonName: sso-test.apps.cluster-zx8zh.dynamic.redhatworkshops.io
  dnsNames:
    - sso-test.apps.cluster-zx8zh.dynamic.redhatworkshops.io
  isCA: false
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: zerossl-production-ec2
  privateKey:
    algorithm: ECDSA
    size: 256
  secretName: rhbk-tls-certificate

