apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rhbk-tst

resources:
  - ns-keycloak.yaml
  - certificate-tls.yaml
  - ../../../../environments/overlays/tst

patches:
  - target:
      name: rhbk-operator-group
      kind: OperatorGroup
      version: v1
      group: operators.coreos.com
    path: patch-operator-group.yaml

