apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../components/apps/keycloak-operator/base
  - ../../../components/apps/keycloak-database/base
  - ../../../components/apps/keycloak/base

patches:
  - target:
      kind: Keycloak
      group: k8s.keycloak.org
      name: keycloak
    path: patch-keycloak.yaml
