apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: rhbk-operator
  annotations:
    app.openshift.io/vcs-uri: 'https://github.com/jmetso/keycloak-gitops'
    argocd.argoproj.io/sync-wave: "100"
spec:
  channel: stable-v26.0
  name: rhbk-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  installPlanApproval: Automatic

