apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rhbk-tls-certificate
  annotations:
    app.openshift.io/vcs-uri: 'https://github.com/jmetso/rhbk-gitops.git'
    argocd.argoproj.io/sync-wave: "50"
spec:
  commonName: sso.apps.cluster-zx8zh.dynamic.redhatworkshops.io
  dnsNames:
    - rhbk.apps.cluster-zx8zh.dynamic.redhatworkshops.io
  isCA: false
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: zerossl-production-ec2
  privateKey:
    algorithm: ECDSA
    size: 256
  secretName: rhbk-tls-certificate

