kind: Namespace
apiVersion: v1
metadata:
  name: rhbk
  annotations:
    app.openshift.io/vcs-uri: 'https://github.com/jmetso/keycloak-gitops'
    argocd.argoproj.io/sync-wave: "50"
  labels:
    kubernetes.io/metadata.name: rhbk
    argocd.argoproj.io/managed-by: openshift-gitops
spec:
  finalizers:
    - kubernetes

